export const PHOTO_LIST_REQUEST = 'PHOTO_LIST_REQUEST'
export const PHOTO_LIST_SUCCESS = 'PHOTO_LIST_SUCCESS'
export const PHOTO_LIST_FAIL = 'PHOTO_LIST_FAIL'

export const PHOTO_DETAILS_REQUEST = 'PHOTO_DETAIL_REQUEST'
export const PHOTO_DETAILS_SUCCESS = 'PHOTO_DETAIL_SUCCESS'
export const PHOTO_DETAILS_FAIL = 'PHOTO_DETAIL_FAIL'